name: billo-blog
health_check:
  initial_delay_seconds: 30
  period_seconds: 10
  timeout_seconds: 5
  success_threshold: 1
  failure_threshold: 5
  http_path: /health
  port: 7654
services:
  - name: api
    github:
      branch: main
      deploy_on_push: true
      repo: betalyra/billo-blog
    build_command: >
      pnpm install && pnpm -r build
    run_command: pnpm --filter "./apps/server" start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    env:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "31337"
